name: CI/CD for Multi-Env Next.js

on:
  push:
    branches:
      - dev
      - sit
      - uat
      - master
  pull_request:
    branches:
      - dev
      - sit
      - uat
      - master

jobs:
  build-dev:
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Build for dev
        run: yarn build:dev

  build-sit:
    runs-on: ubuntu-latest
    if: github.ref_name == 'sit'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Build for sit
        run: yarn build:sit

  build-uat:
    runs-on: ubuntu-latest
    environment:
      name: uat
      url: https://uat.yoursite.com
    if: github.ref_name == 'uat'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Build for uat
        run: yarn build:uat

      - name: Deploy to UAT
        run: echo "Deploying to UAT environment..."

  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://www.yoursite.com
    if: github.ref_name == 'master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Build for prod
        run: yarn build:prod

      - name: Deploy to Production
        run: echo "Deploying to Production environment..."
